#!/bin/bash
# eggd_mosdepth 1.0.0
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    
    # temp dir for downloaded files
    mkdir ~/input/

    # downloads all input files to /in with individual sub dirs, move all to /temp
    dx-download-all-inputs
    find ~/in -type f -name "*" -print0 | xargs -0 -I {} mv {} ~/input

    # get conda and build it, required to install mosdepth
    wget -q https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh 

    bash ~/Miniconda2-latest-Linux-x86_64.sh -b -p $HOME/miniconda

    source ~/miniconda/bin/activate

    conda init

    source ~/.bashrc

    conda config --add channels bioconda
    conda config --add channels conda-forge

    conda install mosdepth

    # # temp dir for downloaded files
    # mkdir ~/temp/

    # dx-download-all-inputs

    # find ~/in -type f -name "*" -print0 | xargs -0 -I {} mv {} ~/temp

    # dx download "$bam" -o bam
    # dx download "$index" -o bam.bai

    mkdir ~/output && cd ~/output

    echo "running mosdepth using:"

    echo "mosdepth $optional_arguments $prefix ~/input/*.bam"

    # run mosdepth
    mosdepth $optional_arguments $prefix ~/input/*.bam
    
    echo "app finished, uploading files"

    # uploads files and passes dx file-id to dx-jobutil-add-output
    # to add to the mosdepth_output array:file

    for file in ./*; 
      do id=$(dx upload $file --brief) && dx-jobutil-add-output --array mosdepth_output "$id"; 
    done

    echo "uploaded"

}
